### ISSUE TITLE
Search live preview/ auto complete

### ISSUE THREAD

**Issue by department19** [fac30/tourism-app#8]
Want the search UI to present suggestions based on what the user currently has within the input field, this will allow assistance on auto complete and preview similar landmarks for the user

**Comment by 3le81** [comment]
- Google Maps Distance Matrix Calculation : **already Implemented**. 
- Display Touristic Places Near Destination : fetch information about touristic places near the destination and display them in a pop-up window. **to be implemented**

**Comment by 3le81** [comment]
Completed!
